services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $entityQuestions: !tagged entity_generator.entity_question
            $propertyQuestions: !tagged entity_generator.property_question
            $attributeQuestions: !tagged entity_generator.attribute_question

    K3ssen\EntityGeneratorBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'
