parameters:
    entity_generator:
        default_bundle: 'App'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
#            $rootDir: '%kernel.root_dir%'
#            $entityTargetDir:
#            $templateDir: "@=service('kernel').locateResource('@EntityGeneratorBundle/templates/skeleton')"

    Kevin3ssen\EntityGeneratorBundle\:
        resource: '../*'
        exclude: '../{Entity,Migrations,Tests}'