parameters:
    # TODO: make sure certain settings cannot be overwritting: for example, the classes set in meta_properties should not be removed.
    default_attributes:
        name: {}
        id:
            meta_properties: 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\PrimitiveMetaPropertyInterface'
            type: 'bool'
            default: false
            requirement_expression: 'metaEntity.getIdProperty() == null or metaEntity.getIdProperty() != metaProperty'
        unique:
            meta_properties: 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\PrimitiveMetaPropertyInterface'
            type: 'bool'
            default: false
        nullable:
            type: 'bool'
            default: false
        length:
            meta_properties: 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\HasLengthInterface'
            type: 'int'
        precision:
            meta_properties: 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\DecimalMetaPropertyInterface'
            type: 'int'
        scale:
            meta_properties: 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\DecimalMetaPropertyInterface'
            type: 'int'
        targetEntity:
            meta_properties: 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\RelationMetaPropertyInterface'
            type: 'object'
            question: 'Kevin3ssen\EntityGeneratorBundle\Command\AttributeQuestion\TargetEntityQuestion'
        referencedColumnName:
            meta_properties: 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\RelationMetaPropertyInterface'
            default: 'id'
            question: null
        orphanRemoval:
            meta_properties:
                - 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\ManyToManyMetaPropertyInterface'
                - 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\OneToManyMetaPropertyInterface'
            type: 'bool'
            default: false
        inversedBy:
            meta_properties:
                - 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\ManyToOneMetaPropertyInterface'
                - 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\OneToOneMetaPropertyInterface'
                - 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\ManyToManyMetaPropertyInterface'
            requirement_expression: 'metaProperty.getMappedBy() == null'
        mappedBy:
            meta_properties:
                - 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\OneToManyMetaPropertyInterface'
                - 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\OneToOneMetaPropertyInterface'
                - 'Kevin3ssen\EntityGeneratorBundle\MetaData\Property\ManyToManyMetaPropertyInterface'
            requirement_expression: 'metaProperty.getMappedBy() == null'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $attributes: '%entity_generator.attributes%'
            $entityQuestions: !tagged entity_generator.entity_question
            $propertyQuestions: !tagged entity_generator.property_question
            $attributeQuestions: !tagged entity_generator.attribute_question
            $overrideSkeletonPath: '%entity_generator.override_skeleton_path%'
            $autoGenerateRepository: '%entity_generator.auto_generate_repository%'
            $bundlesMetaData: '%kernel.bundles_metadata%'

    Kevin3ssen\EntityGeneratorBundle\:
        resource: '../*'
        exclude: '../{Entity,Migrations,Tests}'